name: airea_cough_monitor
description: Simple Airea Cough Monitor

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  fl_chart: ^0.66.0
  percent_indicator: ^4.2.3
  file_picker: ^6.1.1

flutter:
  uses-material-design: true
<<<<<<< HEAD

  assets:
    - assets/
=======
  
  assets:
    - assets/images/
>>>>>>> 2ad5e27f9b9d9f06d934308981174dc6bf2ba2b5
