name: airea_cough_monitor
description: Simple Airea Cough Monitor

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  # intl: ^0.18.1
  provider: ^6.1.1
  fl_chart: ^0.66.0
  percent_indicator: ^4.2.3
  # file_picker: ^10.3.8
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  file_picker: ^6.1.1
  # Open PDFs and Images natively
  open_filex: ^4.3.2
  # For formatting dates 
  intl: ^0.19.0
  # Handling file paths and extensions
  path: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/